### ISSUE TITLE
Setting up kanban board

### ISSUE THREAD

**Issue by igorkol91** [blakbox23/Space-travellers-react-redux#25]
This is the link to our kanban board
https://github.com/blakbox23/Space-travellers-react-redux/projects/1
We are team of 2 students on this project

**Comment by dasileker** [comment]
### **Hi @igorkol91,** 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
_Check the comments under the review._

- First, you have to set up the project cards for `2 people` like the requirements say not for `3 people` [see the screenshot here](https://user-images.githubusercontent.com/61562626/135831679-12bad94d-01cd-45ee-9ce6-4e811ac6ece4.jpeg).
- Second the cards should be distributed equally between the student and your cards do not, I see some cards having the same student two times. [see requirements here](https://user-images.githubusercontent.com/61562626/135831948-f1be2513-8e13-4469-8e43-e088f6a5e6ed.jpeg) and  [see your cards how they are dispatched](https://user-images.githubusercontent.com/61562626/135832240-2ad227cd-8722-4f04-9154-cd5ac6bbc1cf.jpeg) and [how they should be dispatched](https://user-images.githubusercontent.com/61562626/135832446-1adbada0-0a6b-40df-9cd4-63abce2c13ce.jpeg)





## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by blakbox23** [comment]
Thanks for the review @dasileker. We have made the requested changes

**Comment by Davidosky007** [comment]
## Hi @blakbox23 @igorkol91 👋, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
## Congratulations! 🎉 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
